# Generated by Django 5.1.1 on 2025-07-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfor',
            new_name='ContactInfo',
        ),
    ]
